#!/usr/bin/env python3

'''

   Copyright 2016 Dave Fancella

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

'''

import sys
sys.path.insert(0, '')

from davenetgame import exceptions
from davenetgame import paths

import readline
from davenetgame.dispatch import dispatcher
from davenetgame.transport import udp
from davenetgame.protocol import realtime
from davenetgame.protocol import connection
 
host = 'localhost'
port = 8888
name = paths.GetUsername()

print("Starting test client.")

## Help text for commands.
commands = {
    'set' : { 'usage' : "Usage: set (host|port|name) value",
              'desc'  : "Set the host or port to which you intend to connect" },
    'connect' : { 'usage' : "connect [host:port]",
              'desc'  : "Connect to the host and port given, either previously specified, or currently specified" },
    'ping' : { 'usage' : "ping",
               'desc'  : "Ping the server to which you are connected.  You must be connected for this to work."
              },
    'logout' : { 'usage' : "logout",
               'desc'  : "Log out from the server.  You must be connected for this to work."
              },
    'help' : { 'usage' : "help [command]",
              'desc'  : "print(this helpful text.  Alternately, type in a command to see its helpful text." },
    'status' : { 'usage' : "status",
              'desc'  : "Display the status of the current connection." },
    'quit' : { 'usage' : "quit",
              'desc'  : "Quit the test client." },
}

def Help(command=None):
    global commands
    
    if command is not None:
        if command in commands:
            print("%10s : %s" % (command, commands[command]["desc"]) )
            print("%13s %s" % (" ", commands[command]['usage']) )
            print
        else:
            print("Command not found.")
    else:
        for key, value in commands.items():
            print("%10s : %s" % (key, value["desc"] ) )
            print("%13s %s" % (" ", value['usage'] ) )
            print

theClient = None

keepGoing = True

try:
    while(keepGoing) :
        msg = input('')
        
        args = msg.split(" ")
        
        command = args.pop(0)
        
        command = command.lower()
        
        # Ignore simple presses of enter
        if command == '':
            continue
        
        if command == "set":
            if len(args) != 2:
                print("Usage: set (host|port|name) value")
            else:
                if args[0].lower() == "host":
                    host = args[1]
                if args[0].lower() == "port":
                    port = int(args[1])
                if args[0].lower() == "name":
                    name = args[1]
        elif command == "connect":
            if len(args) == 1:
                host, port = args[0].strip().split(":")
                port = int(port)
                
            if host is not None:
                if port is not None:
                    if name is not None:
                        # Create the client object and login
                        if theClient is None:
                            theClient = dispatcher.EventDispatcher()
                            theProtocol = realtime.RealtimeClient( 
                                                        core = True
                                                        )
                            theTransport = transport = udp.Udp(owner = theProtocol,
                                                               serverhost=host,
                                                               serverport=port)
                            theProtocol.BindTransport(theTransport)

                            theClient.AddProtocol(theProtocol)
                            theClient.Start()
                else:
                    print("You must specify a port to connect to")
            else:
                print("You must specify a host to connect to")
        elif command == "logout":
            theClient.Stop()
            theClient = None
        elif command == "quit":
            if theClient is not None:
                theClient.Stop()
                theClient = None
            keepGoing = False
        elif command == "help":
            if len(args) < 1:
                Help()
            else:
                Help(args[0])
        elif command == "ping":
            if theClient is None:
                print("You must be connected to a server to ping!")
            else:
                theProtocol.SendPing()
        elif command == "status":
            if theClient is None:
                print("You are not connected to a server.")
            else:
                for a in theClient.GetConnections():
                    print("{0:3}: {1:40} {2:10} {3:4}".format(a.id(), str(a), connection.statuslist[a.Status()][1], int(a.GetConnectionPing() * 1000) ) )
                #print("Bytes received: " + str(theClient.BytesReceived() ) )
                #print("Bytes sent: " + str(theClient.BytesSent() ) )
                #print("Bytes transferred: " + str(theClient.Bandwidth() ) )
        else:
            print("Command not recognized.")
            
except KeyboardInterrupt:
    print("Quitting due to keyboard interrupt")

if theClient is not None:
    theClient.Stop()
print()



