# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objectcreate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='objectcreate.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12objectcreate.proto\"\x88\x01\n\x0cObjectCreate\x12\n\n\x02id\x18\x01 \x02(\x07\x12\r\n\x05mtype\x18\x02 \x02(\x07\x12\x11\n\ttimestamp\x18\x03 \x02(\x01\x12\r\n\x05otype\x18\x04 \x02(\x07\x12\r\n\x05owner\x18\x05 \x01(\x07\x12\x16\n\x0einitial_values\x18\x06 \x01(\t\x12\x14\n\x0cvalue_string\x18\x07 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_OBJECTCREATE = _descriptor.Descriptor(
  name='ObjectCreate',
  full_name='ObjectCreate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ObjectCreate.id', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mtype', full_name='ObjectCreate.mtype', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='ObjectCreate.timestamp', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='otype', full_name='ObjectCreate.otype', index=3,
      number=4, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='ObjectCreate.owner', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initial_values', full_name='ObjectCreate.initial_values', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value_string', full_name='ObjectCreate.value_string', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['ObjectCreate'] = _OBJECTCREATE

ObjectCreate = _reflection.GeneratedProtocolMessageType('ObjectCreate', (_message.Message,), dict(
  DESCRIPTOR = _OBJECTCREATE,
  __module__ = 'objectcreate_pb2'
  # @@protoc_insertion_point(class_scope:ObjectCreate)
  ))
_sym_db.RegisterMessage(ObjectCreate)


# @@protoc_insertion_point(module_scope)
